CREATE DATABASE ShoppingCartDb;

USE ShoppingCartDb;

CREATE TABLE users (
	id INT PRIMARY KEY AUTO_INCREMENT, 
    name VARCHAR(100)
);

INSERT INTO users (name) VALUES ('John Doe');
INSERT INTO users (name) VALUES ('Scott');
INSERT INTO users (name) VALUES ('Smith');
insert into users (name) values ('Sandy');

SELECT * FROM users;


----------------------------------------------

CREATE TABLE employee (
    empno INT PRIMARY KEY,
    ename VARCHAR(50),
    job VARCHAR(50),
    sal DECIMAL(10,2),
    deptno INT
);


INSERT INTO Emps VALUES(7369,'SMITH','CLERK',800, 20);
INSERT INTO Emps VALUES(7499,'ALLEN','SALESMAN',1600,30);
INSERT INTO Emps VALUES(7521,'WARD','SALESMAN',1250,30);
INSERT INTO Emps VALUES(7566,'JONES','MANAGER',2975,20);
INSERT INTO Emps VALUES(7654,'MARTIN','SALESMAN',1250,30);
INSERT INTO Emps VALUES(7698,'BLAKE','MANAGER',2850,30);
INSERT INTO Emps VALUES(7782,'CLARK','MANAGER',2450,10);
INSERT INTO Emps VALUES(7788,'SCOTT','ANALYST',3000,20);
INSERT INTO Emps VALUES(7839,'KING','PRESIDENT',5000,10);
INSERT INTO Emps VALUES(7844,'TURNER','SALESMAN',1500,30);
INSERT INTO Emps VALUES(7876,'ADAMS','CLERK',1100, 20);
INSERT INTO Emps VALUES(7900,'JAMES','CLERK',950,30);
INSERT INTO Emps VALUES(7902,'FORD','ANALYST',3000,20);
INSERT INTO Emps VALUES(7934,'MILLER','CLERK',1300,10);


INSERT INTO employee (empno, ename, job, sal, deptno)
VALUES (7934,'MILLER','CLERK',1300,10);



-- select commands
SELECT * FROM Emps
SELECT SAL  FROM Emps WHERE Empsno=7934
SELECT COUNT(*) FROM Emps WHERE DEPTNO=40
SELECT EmpsNO, ENAME, JOB,SAL, DEPTNO FROM Emps


-- update record 
UPDATE Emps SET ENAME='NAVEEN', SAL = 4600 WHERE EmpsNO = 7369


-- delete record
DELETE FROM Emps
DELETE FROM Emps WHERE EmpsNO=7369

-- drop table
DROP TABLE Emps


 



